# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Firefox(executable_path='C:\\Users\\Russell Tran\\node_modules\\geckodriver\\geckodriver.exe')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("http://paulgraham.com/")
    self.driver.set_window_size(1229, 688)
    self.driver.find_element(By.CSS_SELECTOR, "table:nth-child(2) td").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "table:nth-child(2) font").text == "Want to start a startup? Get funded by Y Combinator."
    self.driver.find_element(By.CSS_SELECTOR, "area:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td").click()
    assert self.driver.find_element(By.LINK_TEXT, "General and Surprising").text == "General and Surprising"
    assert self.driver.find_element(By.LINK_TEXT, "Charisma / Power").text == "Charisma / Power"
    element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td")
    actions = ActionChains(driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td")
    actions = ActionChains(driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td").click()
    assert self.driver.find_element(By.LINK_TEXT, "The Risk of Discovery").text == "The Risk of Discovery"
  
suite = TestDefaultSuite()
suite.setup_method(suite.test_test1)
suite.test_test1()
suite.teardown_method(suite.test_test1)